spring:
    datasource:
        url: jdbc:postgresql://127.0.0.1:5432/db_adotaaju
        username: user_adotaaju
        password: pass_adotaaju
    jpa:
        database: POSTGRESQL
        show-sql: true
        generate-ddl: true
        hibernate:
          ddl-auto: update
